server:
  port: 8081

spring:
  datasource:
    username: root
    password: yelink123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.102.106:3306/${sql.tableSchema}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 100
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  application: zm
  redis:
    database: 5
    host: 192.168.102.106
    port: 6379
    password: null
    jedis:
      pool:
        max-wait: 8
        max-active: 1000
        max-idle: 100
        min-idle: 1
sql:
  tableSchema: dfs